# This is a basic workflow that is manually triggered
name: Java CI  

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install
      - name: Run unit tests
        run: mvn test

      - name: Run OWASP Dependency Check
        run: mvn org.owasp:dependency-check-maven:check


