# This is a basic workflow that is manually triggered

name: Security Testing

name: Java CI

on:
  push:
    branches: [ "main" ]   # runs on every push to main
  pull_request:
    branches: [ "main" ]   # runs on pull requests targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'   # AdoptOpenJDK distribution

      # Step 3: Cache Maven dependencies (speeds up builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build project
      - name: Build with Maven
        run: mvn clean install -DskipTests

      # Step 5: Run tests
      - name: Run unit tests
        run: mvn test

